### ISSUE TITLE
After examining 7000+ files the library stalls

### ISSUE THREAD

**Issue by marco-schmidt** [mjeanroy/exiftool#37] opened 2019-04-25 20:43 UTC
I'm using exiftool (library) 2.4.0 with exiftool (executable) 11.3.0 for Mac OS X. After successfully examining 7400+ files, nothing happens anymore. I've pressed Suspend on my main thread in Eclipse and get a stacktrace where FileInputStream#readBytes (native method) apparently waits for input. It seems like the pipe between Java application and exiftool is not returning any more data.

Any idea what to do here, any experiences like that? I could regularly close and re-open my ExifTool class object as a workaround.

**Comment by mjeanroy** [comment] 2019-04-29 18:11
Hi @marco-schmidt and thanks for your report.
Are you able to send me a reproducible test case?

In addition to that, can give some details:
- How do you create `ExifTool` instance?
- What is your operating system?
- Which jdk are you using?
- What is the version of `exiftool` you are using?

**Comment by marco-schmidt** [comment] 2019-05-31 06:38
Hi @mjeanroy,

sorry for taking so long to reply, I've been away from all things Internet for a month. Thanks for looking into this.

Your library is being used in https://github.com/marco-schmidt/am/blob/master/src/main/java/am/processor/MetadataExtraction.java after being initialized in https://github.com/marco-schmidt/am/blob/master/src/main/java/am/app/AppConfigLoader.java#L108

I'm using Oracle's Mac OS X JDK 1.8.0_192:
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

The files being examined are on a network volume mounted via afp.

The test case is hard because the program has to examine over 7000 video files in a directory tree. Do you have a directory tree on your system with that many files? I'll try to set up a configuration file where you only need to change a directory path. But maybe my initialization or usage (see above) are flawed so that this won't be necessary.

Thanks again
Marco

**Comment by mjeanroy** [comment] 2019-05-31 07:26
Hi @marco-schmidt,
Thanks, I understand that it can be hard to reproduce in a small repo.
Can you send me a thread dump to understand what could happen when the issue occurs?

**Comment by marco-schmidt** [comment] 2019-06-01 14:49
@mjeanroy 
I waited for the problem to happen, it occurred with file number 7378, and ran
`jstack -l 5030 >> threaddump.log`
Resulting file attached. Thanks again for looking into this.
[threaddump.log](https://github.com/mjeanroy/exiftool/files/3243869/threaddump.log)

**Comment by rkalla** [comment] 2019-08-06 22:49
@marco-schmidt can you try copying the files locally and running the same scan on them and seeing if it stops in relatively the same place?

Would also be curious about watching the Java process as the scan run to see if it's growing and growing - possibly a memory leak.

From the thread dump, and I am RUSTY on these, `pool-1-thread-1` is blocking on the `synchronized` call to `close` - https://github.com/mjeanroy/exiftool/blob/0862fff929587edd60873bc2a9abc96bc64c6431/src/main/java/com/thebuzzmedia/exiftool/core/strategies/StayOpenStrategy.java#L242

Which seems odd to me that it's actively scanning and deemed time to close the thread.

Any chance it's done and the GC is collecting it? How many files are in that folder?

**Comment by mjeanroy** [comment] 2020-06-01 13:40
@marco-schmidt Can you share your code? I have an idea of what may cause the issue, but I'm not 100% sure, since I can't reproduce it.

*Sorry for the very very long delay of my response*

**Comment by vladimirr9** [comment] 2022-05-29 00:22
I have had this same issue too after the 10th call on the same file or so, it appears it happens more on bigger images (mine is like 6000x5000).

**Comment by mjeanroy** [comment] 2022-05-29 11:17
@vladimirr9 Would you be able to share a reproducible test case? Maybe you could invite me to a private repo if you don't want to share it publicly?

**Comment by vladimirr9** [comment] 2022-05-29 11:50
@mjeanroy I made a quick github repo where I managed to isolate it quite well for myself.
https://github.com/vladimirr9/exif-tool-bug-demonstration
After hitting the endpoint from postman 18 or 24 or so times it gets suspended. I think it has to do with the enableStayOpen option, as it works alright I think without it, though disabling it isn't a viable workaround for me due to performance issues. 
In the debugger it doesn't always get stuck at the same line, though it's usually readBytes() as OP noticed.

**Comment by mjeanroy** [comment] 2022-06-02 09:59
Thanks @vladimirr9, it will help a lot.
I'm investigating, I'll let you know very soon.

**Comment by mjeanroy** [comment] 2022-06-05 09:54
@vladimirr9 I think I found the root cause, can you check with the current version on master please?

Here is the how-to, in case you need it:

```
git checkout git@github.com:mjeanroy/exiftool.git
cd exiftool
mvn clean install -DskipTests
```

Then, update the version in your `pom.xml` to `2.6.1-SNAPSHOT`.

**Comment by vladimirr9** [comment] 2022-06-05 10:06
@mjeanroy I tried it out and it no longer enters a suspended state. That seems to be it, thank you very much.

**Comment by mjeanroy** [comment] 2022-06-05 12:21
@vladimirr9 Great, I'm going to release a new version with the fix!

**Comment by mjeanroy** [comment] 2022-06-05 14:58
Version 2.6.1 has just been released with the fix.
Closing issue, please comment if you think it's still not solved.

**Closed by mjeanroy** 2022-06-05 14:58 UTC

**Comment by rkalla** [comment] 2022-10-11 06:59
If the bug is on the ExitTool side, can you try different versions of the
library and see if some exhibit it and others done? The JVM resources the
"ExifTool for Java" are creating are short-lived but if the native tool is
eventually locking up due to a leak between operations then hopefully
that'd be something fixed in a future release.

"stay-open" has been in production for ExifTool for almost a decade, I
added support for it shortly after it was originally introduced so I'd sort
of expect the bugs to be squashed by now... hmmm....

**Comment by mjeanroy** [comment] 2022-10-27 12:34
Hi @rkalla 👋 ,

The issue has been fixed already, it was due to the error stream not being read, so the process was stuck in the `waitFor` call.

I fixed it by redirecting the error stream to the output stream, see [here](https://github.com/mjeanroy/exiftool/commit/425e7c2635751f254c2f3a516182e83f5cd8f940).

**Comment by rkalla** [comment] 2022-10-27 13:47
Great catch Mickael!
