### ISSUE TITLE
close() called when enableStayOpen() prevents from exit on Windows.

### ISSUE THREAD

**Issue by valnaumov** [mjeanroy/exiftool#14] opened 2018-01-19 16:41 UTC
This example from the README

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.thebuzzmedia.exiftool.ExifTool;
import com.thebuzzmedia.exiftool.ExifToolBuilder;
import com.thebuzzmedia.exiftool.Tag;
import com.thebuzzmedia.exiftool.core.StandardTag;
import com.thebuzzmedia.exiftool.exceptions.UnsupportedFeatureException;

import java.io.File;
import java.util.Map;

import static java.util.Arrays.asList;

public class ExifParser {

    private static final Logger log = LoggerFactory.getLogger(ExifParser.class);

    private static final ExifTool exifTool;

    static {
        try {
            exifTool = new ExifToolBuilder().enableStayOpen().build();
        } catch (UnsupportedFeatureException ex) {
            // Fallback to simple exiftool instance.
            exifTool = new ExifToolBuilder().build();
        }
    }

    public static Map<String, Tag> parse(File image) {
        return exifTool.getImageMeta(image, asList(
            StandardTag.ISO,
            StandardTag.X_RESOLUTION,
            StandardTag.Y_RESOLUTION
        ));
    }

    public static void main(String[] args) throws Exception {
        try {
            for (String image : args) {
                System.out.println("Tags: ", ExifParser.parse(new File(image)));
            }
        } finally {
            exifTool.close();
        }
    }
}
```

Hangs on `close()` method.

ExifTool version is 10.73. Java(TM) SE Runtime Environment (build 1.8.0_121-b13). Windows 10.

Thread dump:
```
"pool-1-thread-1@667" prio=5 tid=0xd nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at ExifParser.main(ExifParser.java:51)

"Finalizer@679" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler@680" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"Attach Listener@677" daemon prio=5 tid=0x5 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@678" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE 
```
Could you take a look, please?

**Comment by mjeanroy** [comment] 2018-01-22 12:31
@valnaumov Thanks for the report, I'll look at it as soon as possible, probably in the next few days.

**Comment by valnaumov** [comment] 2018-02-02 16:52
@valnaumov can't test on linux yet.

**Comment by valnaumov** [comment] 2018-02-02 16:52
@mjeanroy can't test on linux yet.

**Comment by motz17** [comment] 2018-02-20 09:15
I can confirm this issue. It can be easily reproduce-able when reading out infos from a hug amount of files . Therefore I wrapped your service into a small tool, which reads out exif infos from one file in a loop https://portal.celum.com/pinaccess/showpin.do?pinCode=8K2fZuErzU2a

usage: 
`java -jar exiftool-1.1.0-SNAPSHOT-shaded.jar "C:\exiftool\exiftool.exe" true 60000 "-g0 -j C:\Users\mha\Pictures\sample.PNG"`

**Comment by mjeanroy** [comment] 2018-02-25 21:23
Hi @valnaumov and @motz17,

Can you try with the master branch if it is ok for you? If everything is ok for you, I'll publish a new release on maven repo.

**Comment by valnaumov** [comment] 2018-02-26 07:08
@mjeanroy works fine. Thanks!

**Comment by mjeanroy** [comment] 2018-02-27 22:49
Hi,
Version 2.3.0 has been released with the fix, it should be available soon on maven repo.
Please comment, or re-open, the issue if the problem is still here.

**Closed by mjeanroy** 2018-02-27 22:49 UTC
